services:
  - type: web
    name: smokeybear-frontend
    env: python
    rootDir: Frontend
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run dashboard.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
    packages:
      - ffmpeg
