services:
  - type: web
    name: OperationSmokeyBear_DSPilots
    env: python
    plan: free
    rootDir: Backend
    buildCommand: |
      apt-get update && apt-get install -y ffmpeg
      pip install -r requirements.txt
    startCommand: uvicorn server:app --host 0.0.0.0 --port $PORT
